package com.revature.revshop.dto;

import lombok.Data;

import java.util.List;


@Data
public class CartResponse {
    private Long userId;                       // ID of the user
    private List<CartItemDto> cartItems;         // List of items currently in the cart
    private double totalPrice;                 // Total price of items in the cart

    // Constructor, getters, and setters can be auto-generated by Lombok
}
