package com.example.demo.dto;

import java.util.List;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;


@Data
@AllArgsConstructor
@NoArgsConstructor
public class CartResponse {
    private String userId;                       // ID of the user
    private List<CartItemDto> cartItems;         // List of items currently in the cart
    private double totalPrice;                 // Total price of items in the cart

    // Constructor, getters, and setters can be auto-generated by Lombok
}
