package com.example.demo.dto;

import lombok.AllArgsConstructor;
import lombok.Data;

@Data
@AllArgsConstructor
public class CartItemDto {
    private Long productId;   // Unique identifier for the product
    private String name;      // Name of the product
    private String skuCode;
    private Double price;     // Price of the product
    private Integer quantity;     // Quantity of the product in the cart

    // Constructor, getters, and setters can be auto-generated by Lombok
}
